### ISSUE TITLE
Addaptation du script de passage de zone a lien

### ISSUE THREAD

**Issue by TitouanRobert** [rte-antares-rpackage/fbAntares#1]
Faire un fichier csv avec un tableau ZONES*ZONES. Des 1 et de -1 serons utilisés pour déterminer le sens du flux. Ce fichier doit être un argument de la fonction.

**Comment by MarionLi0** [comment]
Pour la première version, ajouter un paramètre, nom?
Possibilités : 

1. CWE : 

- BE = be.fr + be.de + be.nl
- DE = -be.de + de.fr + de.nl
- FR = -be.fr - de.fr
- NL = -be.nl - de.nl

2. CWE_at : 

- BE = be.fr + be.de + be.nl
- DE = -be.de + de.fr + de.nl - at.de
- FR = -be.fr - de.fr
- NL = -be.nl - de.nl
- AT = at.de

3. customised : 
csv ?


Dans tous les cas, il faudrait un affichage pour vérification dans la console
