### ISSUE TITLE
études antares

### ISSUE THREAD

**Issue by JulienBretteville** [rte-antares-rpackage/fbAntares#14]
Ajouter de nouvelles études en fichiers tests qui remplacent ex_test.tgz et exemple_test.tgz pour pouvoir tester facilement les fonctions initFlowbased et plotNetPositionFB

**Comment by TitouanRobert** [comment]
Dans l'étude actuelle (inst\input\model\antaresInput), il manque des correspondances entre Id_day du fichier  second_member.txt et les éléments présent dans ts.txt. J'ajoute les éléments à la main pour la première vague de test, nous générons une étude avec tous les Id_day par la suite.

**Comment by TitouanRobert** [comment]
Ajouter le lien DE-AT dans ces nouvelles études pour pouvoir tester initFlowBased avec  areaName = "cwe_at"

**Comment by TitouanRobert** [comment]
check if pointX is rigth (and no pointY))
