### ISSUE TITLE
Trop de lignes pour la CAH

### ISSUE THREAD

**Issue by JulienBretteville** [rte-antares-rpackage/fbAntares#3]
Pour 12 jours types, nous avons 41 454 lignes, ce qui est trop pour construire la matrice de distance nécessaire à la CAH. On peut envisager un kmeans mais si tu as une meilleure solution, n'hésite pas.

**Comment by MarionLi0** [comment]
k-means puis CAH
Attente de validation par Titouan pour le définitif

**Comment by MarionLi0** [comment]
Gestion RAM

**Comment by TitouanRobert** [comment]
Ok pour moi, si ce n'est pas fait penser à bloquer la graine aléatoire.

**Comment by TitouanRobert** [comment]
Si 5000 lignes ou moins -> CAH sinon kmeans + CAH
